### ISSUE TITLE
Optimization of unloading a OSM layer into the loam format

### ISSUE THREAD

**Issue by eugenever** [DougLau/earthwyrm#3]
Let's say we want to upload a large region to the `loam` format, for example, all of Europe. The `building` layer will have a large number of objects that will fit in memory and it may not be enough. As far as I understand, the `get_objs_and_deps` method works like this. Does it make sense to read objects from `OsmPbfReader` in chunks (I think I can write such functionality) and write these chunks in `BulkWriter.` Is it possible to somehow provide such an API for `BulkWriter`? Thus, the entire planet can be unloaded.

**Comment by DougLau** [comment]
I may be missing something, but I don't think any changes would be necessary to BulkWriter.  It already works in a "streaming" fashion, and the "finish" function uses mmap so that the OS will page memory out to disk as necessary.

**Comment by eugenever** [comment]
Thanks for clarifying! I will try to optimize `get_objs_and_deps.` The topic can be closed.
